# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'interface_operador.ui'
#
# Created by: PyQt5 UI code generator 5.9.2
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(636, 495)
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 199, 196))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 227, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 99, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 133, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 227, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 199, 196))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 227, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 99, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 133, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 227, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.ToolTipText, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 99, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 199, 196))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Button, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Light, brush)
        brush = QtGui.QBrush(QtGui.QColor(229, 227, 225))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Midlight, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 99, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Dark, brush)
        brush = QtGui.QBrush(QtGui.QColor(135, 133, 130))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Mid, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 99, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 255))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.BrightText, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 99, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ButtonText, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 199, 196))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Base, brush)
        brush = QtGui.QBrush(QtGui.QColor(136, 138, 133))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Window, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Shadow, brush)
        brush = QtGui.QBrush(QtGui.QColor(203, 199, 196))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.AlternateBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.NoRole, brush)
        brush = QtGui.QBrush(QtGui.QColor(255, 255, 220))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipBase, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.ToolTipText, brush)
        Dialog.setPalette(palette)
        font = QtGui.QFont()
        font.setPointSize(12)
        Dialog.setFont(font)
        self.verticalLayout = QtWidgets.QVBoxLayout(Dialog)
        self.verticalLayout.setObjectName("verticalLayout")
        self.tabWidget = QtWidgets.QTabWidget(Dialog)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.tabWidget.setFont(font)
        self.tabWidget.setObjectName("tabWidget")
        self.tabCamera = QtWidgets.QWidget()
        self.tabCamera.setObjectName("tabCamera")
        self.gridLayout_3 = QtWidgets.QGridLayout(self.tabCamera)
        self.gridLayout_3.setObjectName("gridLayout_3")
        self.pushButtonLiberaAcesso = QtWidgets.QPushButton(self.tabCamera)
        self.pushButtonLiberaAcesso.setObjectName("pushButtonLiberaAcesso")
        self.gridLayout_3.addWidget(self.pushButtonLiberaAcesso, 1, 0, 1, 1)
        self.graphicsView = QtWidgets.QGraphicsView(self.tabCamera)
        self.graphicsView.setObjectName("graphicsView")
        self.gridLayout_3.addWidget(self.graphicsView, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabCamera, "")
        self.tabAcessos = QtWidgets.QWidget()
        self.tabAcessos.setObjectName("tabAcessos")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.tabAcessos)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.textBrowserLogs = QtWidgets.QTextBrowser(self.tabAcessos)
        self.textBrowserLogs.setObjectName("textBrowserLogs")
        self.gridLayout_2.addWidget(self.textBrowserLogs, 0, 0, 1, 1)
        self.tabWidget.addTab(self.tabAcessos, "")
        self.tabCadastro = QtWidgets.QWidget()
        self.tabCadastro.setObjectName("tabCadastro")
        self.labelRG = QtWidgets.QLabel(self.tabCadastro)
        self.labelRG.setGeometry(QtCore.QRect(70, 80, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelRG.setFont(font)
        self.labelRG.setObjectName("labelRG")
        self.labelNome = QtWidgets.QLabel(self.tabCadastro)
        self.labelNome.setGeometry(QtCore.QRect(70, 30, 51, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.labelNome.setFont(font)
        self.labelNome.setObjectName("labelNome")
        self.lineEditRG = QtWidgets.QLineEdit(self.tabCadastro)
        self.lineEditRG.setGeometry(QtCore.QRect(140, 80, 341, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditRG.setFont(font)
        self.lineEditRG.setObjectName("lineEditRG")
        self.lineEditNome = QtWidgets.QLineEdit(self.tabCadastro)
        self.lineEditNome.setGeometry(QtCore.QRect(140, 30, 341, 27))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.lineEditNome.setFont(font)
        self.lineEditNome.setObjectName("lineEditNome")
        self.pushButtonCadastrar = QtWidgets.QPushButton(self.tabCadastro)
        self.pushButtonCadastrar.setGeometry(QtCore.QRect(230, 380, 151, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.pushButtonCadastrar.setFont(font)
        self.pushButtonCadastrar.setObjectName("pushButtonCadastrar")
        self.labelSelectImgs = QtWidgets.QLabel(self.tabCadastro)
        self.labelSelectImgs.setGeometry(QtCore.QRect(20, 130, 291, 41))
        self.labelSelectImgs.setObjectName("labelSelectImgs")
        self.pushButtonSelectImgs = QtWidgets.QPushButton(self.tabCadastro)
        self.pushButtonSelectImgs.setGeometry(QtCore.QRect(340, 134, 181, 31))
        self.pushButtonSelectImgs.setObjectName("pushButtonSelectImgs")
        self.labelImg1 = QtWidgets.QLabel(self.tabCadastro)
        self.labelImg1.setGeometry(QtCore.QRect(170, 180, 271, 21))
        self.labelImg1.setText("")
        self.labelImg1.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImg1.setObjectName("labelImg1")
        self.labelImg2 = QtWidgets.QLabel(self.tabCadastro)
        self.labelImg2.setGeometry(QtCore.QRect(170, 220, 271, 21))
        self.labelImg2.setText("")
        self.labelImg2.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImg2.setObjectName("labelImg2")
        self.labelImg3 = QtWidgets.QLabel(self.tabCadastro)
        self.labelImg3.setGeometry(QtCore.QRect(170, 260, 271, 21))
        self.labelImg3.setText("")
        self.labelImg3.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImg3.setObjectName("labelImg3")
        self.labelImg4 = QtWidgets.QLabel(self.tabCadastro)
        self.labelImg4.setGeometry(QtCore.QRect(170, 300, 271, 21))
        self.labelImg4.setText("")
        self.labelImg4.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImg4.setObjectName("labelImg4")
        self.labelImg5 = QtWidgets.QLabel(self.tabCadastro)
        self.labelImg5.setGeometry(QtCore.QRect(170, 340, 271, 21))
        self.labelImg5.setText("")
        self.labelImg5.setAlignment(QtCore.Qt.AlignCenter)
        self.labelImg5.setObjectName("labelImg5")
        self.labelAviso = QtWidgets.QLabel(self.tabCadastro)
        self.labelAviso.setGeometry(QtCore.QRect(150, 260, 311, 21))
        palette = QtGui.QPalette()
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Active, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(204, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(0, 0, 0))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Inactive, QtGui.QPalette.Text, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 99, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.WindowText, brush)
        brush = QtGui.QBrush(QtGui.QColor(101, 99, 98))
        brush.setStyle(QtCore.Qt.SolidPattern)
        palette.setBrush(QtGui.QPalette.Disabled, QtGui.QPalette.Text, brush)
        self.labelAviso.setPalette(palette)
        font = QtGui.QFont()
        font.setBold(True)
        font.setWeight(75)
        self.labelAviso.setFont(font)
        self.labelAviso.setText("")
        self.labelAviso.setAlignment(QtCore.Qt.AlignCenter)
        self.labelAviso.setObjectName("labelAviso")
        self.tabWidget.addTab(self.tabCadastro, "")
        self.verticalLayout.addWidget(self.tabWidget)

        self.retranslateUi(Dialog)
        self.tabWidget.setCurrentIndex(0)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "TCC"))
        self.pushButtonLiberaAcesso.setText(_translate("Dialog", "Liberar Acesso"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCamera), _translate("Dialog", "Câmera"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabAcessos), _translate("Dialog", "Acessos"))
        self.labelRG.setText(_translate("Dialog", "      RG :"))
        self.labelNome.setText(_translate("Dialog", "Nome :"))
        self.pushButtonCadastrar.setText(_translate("Dialog", "Cadastrar"))
        self.labelSelectImgs.setText(_translate("Dialog", "Selecione de 3 a 5 imagens do usuário:"))
        self.pushButtonSelectImgs.setText(_translate("Dialog", "Selecionar Imagens"))
        self.tabWidget.setTabText(self.tabWidget.indexOf(self.tabCadastro), _translate("Dialog", "Cadastro"))

